### ISSUE TITLE
world logo not working

### ISSUE THREAD

**Issue by dsakura** [TheEpicSnowWolf/Foundry-VTT-Prettier-Login-Screen#8]
Hello! Thanks for the code. But I'm trying to put the image, with address in the public/ui folder in the code and it doesn't work. Need an image hosted elsewhere online? A better solution for me would be to change the world name font, if you know how to do that from the code, I'm grateful, to use modest-condensed.
Thank you again

**Comment by TheEpicSnowWolf** [comment]
Hi @dsakura! Apologies for the late response, I really should try to get my GitHub notifications working properly again. What does the URL look like you used to get to the image in the `ui` folder? To access it from the `css` directory, it should probably be something like this: `--login-world-logo: url("../ui/logo.png");`

**Comment by TheEpicSnowWolf** [comment]
Thank you for the update, the issue here is that in CSS, absolute paths like this are always related to the web URL rather than the filepath on your local machine. The easiest way to fix this is use a relative path instead (which will look for your image based on the directory the `style.css` is located).

Could you try this please: `--login-world-logo: url("../ui/footherois.png");`

The `../` is instructing the CSS to basically look in the directory "above" it's current location, which is where the `ui` directory should be located.

**Comment by dsakura** [comment]
Working perfect now. Many thanks!
